#name of the action
name : Temperature

#on the following events, the workflow is triggered
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  #name of the job that is run
  temperature:
    #an ubuntu virtual machine is created for the workflow to run
    runs-on: ubuntu-latest
    steps:        
    #this is the action to checkout code, find more at https://github.com/actions/checkout
    - uses: actions/checkout@v2
    - name: Write temperature
      #the script to get the temperature and write it into a file
      run: |
        python get_temperature.py
    
    #this is the action to commit files added/modified during the workflow
    #find more at : https://github.com/EndBug/add-and-commit
    #if there is a change to any files or new files added, the code will be committed.
    - uses: EndBug/add-and-commit@v8
      with:
          author_name: Namya #replace it with your name
          message : Temperature written
